# SPDX-License-Identifier: Apache-2.0
#
# Hermetic npm artifact packaging: `packages.npm-artifacts` (aliased as
# `default`) packs every publishable workspace package with its real `prepack`
# pipeline, and `checks.npm-artifacts-contents` audits the resulting tarballs.
{ self, ... }:
{
  perSystem =
    {
      pkgs,
      config,
      ...
    }:
    let
      lib = pkgs.lib;

      compact-midnight = config.toolchain.compact-midnight;
      compact-toolchain = config.toolchain.compact-toolchain;
      midnight-circuit-params = config.toolchain.midnight-circuit-params;

      rootFileNames = [
        ".npmrc"
        ".nvmrc"
        "LICENSE" # pnpm pack walks up to the workspace root for it
        "package.json"
        "pnpm-lock.yaml"
        "pnpm-workspace.yaml"
        "tsconfig.json"
        "turbo.json"
      ];

      # Only what influences `pnpm fetch`, so irrelevant root-file edits
      # cannot churn the fixed-output store hash.
      manifestFileNames = [
        ".npmrc"
        "package.json"
        "pnpm-lock.yaml"
        "pnpm-workspace.yaml"
      ];

      # Regenerated by `prepack` inside the sandbox.
      excludedDirNames = [
        ".pi"
        ".turbo"
        "core-compact-staging"
        "coverage"
        "dist"
        "managed"
        "node_modules"
        "reports"
        "result"
      ];

      relativeToSelf =
        path: lib.removePrefix (toString self + "/") (toString path);

      # Auto-discovery: every non-private packages/*/package.json.
      publishablePackages =
        let
          packagesRoot = "${self}/packages";
          entries = builtins.readDir packagesRoot;
          packageDirs = lib.attrNames (lib.filterAttrs (_: type: type == "directory") entries);
          manifests = map (dir: {
            dir = "packages/${dir}";
            manifest = builtins.fromJSON (builtins.readFile "${packagesRoot}/${dir}/package.json");
          }) packageDirs;
          publishable = builtins.filter ({ manifest, ... }: !(manifest.private or false)) manifests;
        in
        map
          (
            { dir, manifest }:
            let
              baseName = lib.last (lib.splitString "/" manifest.name);
              # npm tarball filename convention: scope kept, `@` and `/`
              # become `-` (`@scope/name@1.0.0` -> `scope-name-1.0.0.tgz`).
              tarballName = "${lib.replaceStrings [ "@" "/" ] [ "" "-" ] manifest.name}-${manifest.version}.tgz";
            in
            {
              inherit dir;
              name = manifest.name;
              version = manifest.version;
              inherit baseName tarballName;
            }
          )
          publishable;

      manifestSource = lib.cleanSourceWith {
        name = "npm-manifests-src";
        src = self;
        filter =
          path: type:
          let
            rel = relativeToSelf path;
            components = lib.splitString "/" rel;
            depth = builtins.length components;
          in
          if builtins.head components == "packages" then
            depth <= 2 || (depth == 3 && baseNameOf path == "package.json")
          else
            depth == 1 && lib.elem (baseNameOf path) manifestFileNames;
      };

      workspaceSource = lib.cleanSourceWith {
        name = "npm-workspace-src";
        src = self;
        filter =
          path: type:
          let
            rel = relativeToSelf path;
            components = lib.splitString "/" rel;
            depth = builtins.length components;
          in
          if builtins.head components == "packages" then
            !(type == "directory" && lib.elem (baseNameOf path) excludedDirNames)
          else
            depth == 1 && lib.elem (baseNameOf path) rootFileNames;
      };

      pnpmOfflineStore = import ./pnpm-offline-store.nix {
        inherit lib;
        stdenv = pkgs.stdenv;
        nodejs = pkgs.nodejs_24;
        cacert = pkgs.cacert;
      };

      offlineStore = pnpmOfflineStore { src = manifestSource; };

      npmTarball = import ./npm-tarball.nix;

      tarballFor =
        pkg:
        npmTarball {
          inherit lib pkg;
          stdenv = pkgs.stdenv;
          nodejs = pkgs.nodejs_24;
          inherit compact-midnight compact-toolchain midnight-circuit-params;
          src = workspaceSource;
          inherit offlineStore;
        };

      npm-artifacts = pkgs.linkFarm "npm-artifacts" (
        map (pkg: {
          name = pkg.tarballName;
          path = "${tarballFor pkg}/${pkg.tarballName}";
        }) publishablePackages
      );

      # Audits each tarball for the distribution invariants; failures name
      # the offending tarball and the violation.
      npmArtifactsContentsCheck =
        let
          artifacts = npm-artifacts;
          assertTarball =
            pkg:
            let
              tgz = "${artifacts}/${pkg.tarballName}";
            in
            ''
              tgz="${tgz}"
              if [ ! -f "$tgz" ]; then
                echo "ERROR: npm-artifacts-contents: tarball ${pkg.tarballName} (package ${pkg.name}) is missing from the npm-artifacts output" >&2
                exit 1
              fi
              work="$(mktemp -d)"
              tar -xzf "$tgz" -C "$work"
              root="$work/package"
              violation() {
                echo "ERROR: npm-artifacts-contents: tarball ${pkg.tarballName} (package ${pkg.name}): $1" >&2
                exit 1
              }
              manifest_version="$(jq -r '.version' "$root/package.json")"
              if [ "$manifest_version" != "${pkg.version}" ]; then
                violation "tarball filename version (${pkg.version}) does not match the packed manifest version ($manifest_version)"
              fi
              if [ -z "$(find "$root/dist" -type f -print -quit)" ]; then
                violation "compiled distribution output (package/dist/) is missing or empty"
              fi
              if ! ls "$root"/dist/managed/*/contract/index.js >/dev/null 2>&1; then
                violation "managed contract index (package/dist/managed/<contract>/contract/index.js) is missing"
              fi
              if [ -z "$(find "$root/src" -type f -name '*.compact' -print -quit)" ]; then
                violation "compact contract sources (package/src/**/*.compact) are missing"
              fi
              if [ -z "$(find "$root/scripts" -type f -name '*.mjs' -print -quit)" ]; then
                violation "build helper scripts (package/scripts/*.mjs) are missing"
              fi
              if maps="$(find "$root/dist/managed" -type f -name '*.map' -print)" && [ -n "$maps" ]; then
                echo "$maps" >&2
                violation "managed-code source maps are shipped under package/dist/managed/"
              fi
              if secrets="$(find "$root" -type f \( -name '*.pem' -o -name '*.key' -o -name '.env' -o -name '.env.*' \) -print)" && [ -n "$secrets" ]; then
                echo "$secrets" >&2
                violation "possible secret material is shipped in the tarball"
              fi
              rm -rf "$work"
            '';
        in
        pkgs.runCommand "check-npm-artifacts-contents"
          {
            nativeBuildInputs = [ pkgs.jq ];
            meta.description = "Audits the npm-artifacts tarballs for the distribution invariants (dist output, compact sources, scripts, no managed source maps, version consistency)";
          }
          ''
            set -euo pipefail
            ${lib.concatStrings (map assertTarball publishablePackages)}
            touch "$out"
          '';
    in
    {
      packages.npm-artifacts = npm-artifacts;
      packages.default = npm-artifacts;

      checks.npm-artifacts-contents = npmArtifactsContentsCheck;
    };
}
